In [1]:
import numpy as np 
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =  pd.read_csv("/kaggle/input/crowdedness-at-the-campus-gym/data.csv")

In [3]:
df.head()

,number_people,date,timestamp,day_of_week,is_weekend,is_holiday,temperature,is_start_of_semester,is_during_semester,month,hour
0,37,2015-08-14 17:00:11-07:00,61211,4,0,0,71.76,0,0,8,17
1,45,2015-08-14 17:20:14-07:00,62414,4,0,0,71.76,0,0,8,17
2,40,2015-08-14 17:30:15-07:00,63015,4,0,0,71.76,0,0,8,17
3,44,2015-08-14 17:40:16-07:00,63616,4,0,0,71.76,0,0,8,17
4,45,2015-08-14 17:50:17-07:00,64217,4,0,0,71.76,0,0,8,17

In [4]:
x = df[["number_people", "temperature", "month"]]
y= df["day_of_week"]

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.3,random_state=42)

In [6]:
import numpy as np
print(np.isnan(x_train).any())
print(np.isinf(x_train).any())
print(np.isnan(y_train).any())
print(np.isinf(y_train).any())

number_people    False
temperature      False
month            False
dtype: bool
number_people    False
temperature      False
month            False
dtype: bool
False
False

In [7]:
x_train = np.nan_to_num(x_train)
y_train = np.nan_to_num(y_train)

In [8]:
from sklearn.linear_model import LinearRegression
mlr= LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [9]:
print("intercept:", mlr.intercept_)
print("coefficiants:")
list(zip(x,mlr.coef_))

intercept: 1.9638674442803996
coefficiants:

[('number_people', -0.017052377974856536),
 ('temperature', 0.026786841984463898),
 ('month', -0.007340042513720734)]

In [10]:
y_pred = mlr.predict(x_test)
print("prediction for test set:{}".format(y_pred))

prediction for test set:[3.47457178 3.09394384 3.0139225  ... 3.32878802 2.79455278 3.46732518]

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [11]:
mlr_dif = pd.DataFrame({"actual value: ":y_test,"predited value: ":y_pred})
mlr_dif.head()

       actual value:   predited value:
44802               1          3.474572
51279               6          3.093944
36816               6          3.013922
2503                1          2.635295
53035               5          3.479891

In [12]:
from sklearn import metrics
meansquare = metrics.mean_squared_error(y_test, y_pred)
print("R-squared: {:.2f}".format(mlr.score(x, y) * 100))
print("Mean Squared Error: ", meansquare)

R-squared: 3.23
Mean Squared Error:  3.881741484788899

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"